[skip ci]

diff --git a/.github/scripts/install_tests b/.github/scripts/install_tests
--- a/.github/scripts/install_tests
+++ b/.github/scripts/install_tests
@@ -1,14 +1,26 @@
 #!/bin/bash
 
-set -x
-
 . /etc/os-release
 
-echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
-curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
+case $ID in
+        ubuntu)
+                set -x
 
-sudo apt-get update -qq
-sudo apt-get install -qq -y uidmap podman slirp4netns
+                echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
+                curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
 
-sudo truncate -s 0 /etc/containers/registries.conf
-echo -e "[registries.search]\nregistries = ['quay.io', 'docker.io', 'registry.centos.org', 'registry.fedoraproject.org', 'registry.access.redhat.com']\n\n[registries.insecure]\nregistries = []\n\n[registries.block]\nregistries = []" | sudo tee /etc/containers/registries.conf
+                sudo apt-get update -qq
+                sudo apt-get install -qq -y uidmap podman slirp4netns
+
+                sudo truncate -s 0 /etc/containers/registries.conf
+                echo -e "[registries.search]\nregistries = ['quay.io', 'docker.io', 'registry.centos.org', 'registry.fedoraproject.org', 'registry.access.redhat.com']\n\n[registries.insecure]\nregistries = []\n\n[registries.block]\nregistries = []" | sudo tee /etc/containers/registries.conf
+                ;;
+        fedora)
+                set -x
+                
+                sudo dnf install -qy buildah
+                ;;            
+	*)
+		echo "ERROR: Distro $ID is currently unsupported!!" 1>&2
+		exit 1
+esac
